### ISSUE TITLE
xcube requirements don't fit with aiobotocore requirements leading to a import error

### ISSUE THREAD

**Issue by Sonicious** [xcube-dev/xcube#1076] opened 2024-09-26 10:19 UTC
Initial installation (outside DeepESDL, Ubuntu 24.04.1 LTS, Conda 24.7.1 ) with:

```bash
conda create -n xcubetest python pip xcube 
conda activate xcubetest
```

importing of `xcube.core.store` fails with `ImportError: cannot import name 'resolve_auth_type' from 'botocore.auth'`

Since this sounded and turned out as an error in aiobotocore/botocore, `pip check` should show dependencies here:

```bash
xcube 1.7.0 has requirement botocore>=1.34.51, but you have botocore 1.34.31.
aiobotocore 2.15.1 has requirement botocore<1.35.24,>=1.35.16, but you have botocore 1.34.31.
```

**Comment by pont-us** [comment] 2024-10-02 10:57
Since we're still unable to reproduce the error I'm closing this issue for now. If the solution suggested above didn't help (`conda install -c conda-forge botocore=1.35.23`) and you still need assistance, you can post an update and we'll reopen the issue and continue debugging.

**Closed by pont-us** 2024-10-02 10:57 UTC
